import PDFDocument from "pdfkit";
import { format, type Cents } from "@tote/core";
import { getLedger, getTenant } from "@/lib/tenant";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

const fmt = (c: bigint) => format(c as Cents);

/**
 * Owner statement as a real downloadable PDF — the document an owner receives.
 * Every figure is derived from the immutable ledger, so the statement always
 * reconciles to the books.
 */
export async function GET(
  _req: Request,
  { params }: { params: { ownerId: string } },
): Promise<Response> {
  const { orgId, legalEntityId, legalEntities } = await getTenant();
  const party = await prisma.party.findFirst({ where: { id: params.ownerId, orgId } });
  if (!party) return new Response("Not found", { status: 404 });

  const ledger = await getLedger();
  const [receivable, pursePayable, net, lines] = await Promise.all([
    ledger.balanceOf("ACCOUNTS_RECEIVABLE", { partyId: party.id }),
    ledger.balanceOf("OWNER_PURSE_PAYABLE", { partyId: party.id }),
    ledger.netPosition(party.id),
    prisma.journalLine.findMany({
      where: { orgId, legalEntityId, partyId: party.id },
      include: { entry: true },
      orderBy: { entry: { date: "desc" } },
      take: 60,
    }),
  ]);
  const barn = legalEntities.find((e) => e.id === legalEntityId)?.name ?? "Barn";

  const pdf = await buildPdf({ barn, ownerName: party.name, receivable, pursePayable, net, lines });

  return new Response(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="statement-${party.name.replace(/\s+/g, "-").toLowerCase()}.pdf"`,
    },
  });
}

interface Line {
  entry: { date: Date; memo: string | null };
  accountKind: string;
  debit: bigint;
  credit: bigint;
}

function buildPdf(data: {
  barn: string;
  ownerName: string;
  receivable: bigint;
  pursePayable: bigint;
  net: bigint;
  lines: Line[];
}): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  const GREEN = "#0e7c66";
  const MUTED = "#647a6c";
  const today = new Date().toISOString().slice(0, 10);

  // Letterhead
  doc.fillColor(GREEN).font("Helvetica-Bold").fontSize(22).text(data.barn, 50, 50);
  doc.fillColor(MUTED).font("Helvetica").fontSize(10).text("Racing accounting — statement", 50, 78);
  doc.fillColor("#111b16").font("Helvetica-Bold").fontSize(16).text("Owner Statement", 400, 50, { align: "right", width: 145 });
  doc.fillColor(MUTED).font("Helvetica").fontSize(10).text(today, 400, 74, { align: "right", width: 145 });

  doc.moveTo(50, 100).lineTo(545, 100).strokeColor("#e2e6e2").stroke();

  // Bill-to
  doc.fillColor(MUTED).fontSize(9).text("STATEMENT FOR", 50, 116);
  doc.fillColor("#111b16").font("Helvetica-Bold").fontSize(14).text(data.ownerName, 50, 128);

  // Summary tiles
  const tileY = 165;
  summaryTile(doc, 50, tileY, "Receivable", fmt(data.receivable), MUTED);
  summaryTile(doc, 215, tileY, "Purse due to you", fmt(data.pursePayable), MUTED);
  summaryTile(doc, 380, tileY, "Net position", fmt(data.net), GREEN);

  // Table
  let y = 240;
  doc.fillColor(MUTED).font("Helvetica-Bold").fontSize(9);
  doc.text("DATE", 50, y);
  doc.text("DESCRIPTION", 120, y);
  doc.text("CHARGE", 360, y, { width: 85, align: "right" });
  doc.text("CREDIT", 460, y, { width: 85, align: "right" });
  y += 14;
  doc.moveTo(50, y).lineTo(545, y).strokeColor("#e2e6e2").stroke();
  y += 8;

  doc.font("Helvetica").fontSize(9).fillColor("#111b16");
  for (const l of data.lines) {
    if (y > 780) {
      doc.addPage();
      y = 50;
    }
    const charge = l.accountKind === "ACCOUNTS_RECEIVABLE" ? l.debit : 0n;
    const credit =
      l.accountKind === "ACCOUNTS_RECEIVABLE"
        ? l.credit
        : l.accountKind === "OWNER_PURSE_PAYABLE"
          ? l.credit
          : 0n;
    doc.fillColor("#111b16").text(l.entry.date.toISOString().slice(0, 10), 50, y);
    doc.text(l.entry.memo ?? "—", 120, y, { width: 230, ellipsis: true });
    doc.text(charge > 0n ? fmt(charge) : "", 360, y, { width: 85, align: "right" });
    doc.text(credit > 0n ? fmt(credit) : "", 460, y, { width: 85, align: "right" });
    y += 18;
  }

  // Footer
  doc.fillColor(MUTED).fontSize(8).text(
    "Generated by Tote. Every figure is derived from an immutable, always-balanced ledger.",
    50,
    805,
    { align: "center", width: 495 },
  );

  doc.end();
  return done;
}

function summaryTile(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  label: string,
  value: string,
  valueColor: string,
) {
  doc.roundedRect(x, y, 150, 55, 6).strokeColor("#e2e6e2").stroke();
  doc.fillColor("#647a6c").font("Helvetica").fontSize(8).text(label.toUpperCase(), x + 12, y + 12);
  doc.fillColor(valueColor).font("Helvetica-Bold").fontSize(16).text(value, x + 12, y + 26);
}
